### ISSUE TITLE
Action stopped working?

### ISSUE THREAD

**Issue by hynek** [pdm-project/update-deps-action#2]
My update action suddenly stopped working, without me knowingly changing anything: https://github.com/hynek/build-and-inspect-python-package/actions/runs/5635520026/job/15266612546

I use it like this:

```yaml
---
name: Upgrade dependencies

on:
  workflow_dispatch: # Allow running on-demand
  schedule:
    # Runs every 1st of Month at 3:25 UTC
    - cron: "25 3 1 * *"

env:
  FORCE_COLOR: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pdm-project/update-deps-action@v1.2
        with:
          commit-message: Update dependencies
          update-strategy: all

      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.x
          cache: true

      - run: pdm export --format requirements >tools.txt
```

And the errors look like this:

```
Download action repository 'actions/checkout@v3' (SHA:c85c95e3d7251135ab7dc9ce3241c5835cc595a9)
Download action repository 'pdm-project/update-deps-action@v1.2' (SHA:526f93f45baf21b7354894646eec869e32ad3d74)
Download action repository 'pdm-project/setup-pdm@v3' (SHA:2d86acd19c593b7877c4ac2745277c4a5b5d376c)
Error: pdm-project/update-deps-action/v1.2/action.yml (Line: 30, Col: 7): Required property is missing: shell
Error: pdm-project/update-deps-action/v1.2/action.yml (Line: 31, Col: 11):
Error: pdm-project/update-deps-action/v1.2/action.yml (Line: 30, Col: 7): Required property is missing: shell
Error: pdm-project/update-deps-action/v1.2/action.yml (Line: 31, Col: 11): Unexpected symbol: '"true"'. Located at position 27 within expression: inputs.install-plugins == "true"
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. pdm-project/update-deps-action/v1.2/action.yml (Line: 30, Col: 7): Required property is missing: shell,pdm-project/update-deps-action/v1.2/action.yml (Line: 31, Col: 11): Unexpected symbol: '"true"'. Located at position 27 within expression: inputs.install-plugins == "true"
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load pdm-project/update-deps-action/v1.2/action.yml
```

**Comment by frostming** [comment]
Fixed on v1.3. Somehow forgot to push the changes.
